In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

70
0.25541744016201184


In [2]:
#create n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[78 52 17]
[[55  0 73 67]
 [79 80 15  7]
 [23 26 12 42]]
[[[45  8]
  [96 26]
  [48 41]
  [62 72]]

 [[81 94]
  [ 6  9]
  [71 90]
  [76 37]]

 [[ 2  0]
  [47 43]
  [ 1 33]
  [93 26]]]


In [3]:
#create n-dimensional array with random floating point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.024323011529244987
[0.51340161 0.04393542 0.71177043]
[[0.88372485 0.68574116 0.21266321]
 [0.72566002 0.12572596 0.0083488 ]]


In [7]:
a = random.randint(100,size=(3,2)).ravel()
a

array([91, 35, 69, 42, 74, 66])

In [8]:
#single element will be selected
random.choice(a)

91

In [10]:
#for generating an array with the given shape and elements from given list
random.choice([1,2,3,4,5],size=(4,4))

array([[1, 2, 4, 4],
       [2, 4, 4, 4],
       [3, 4, 1, 3],
       [5, 2, 1, 3]])

### pandas:
1. Data manipulation,analysis and cleaning
2. Tabular, Unlabelled

### Creating a DataFrame
1. using 2 dictonaries